### ISSUE TITLE
Please specify license

### ISSUE THREAD

**Issue by diffway** [dvingerh/transmission-renamer#3]
First of all - thanks for the efforts. RPC isn't simple to work using available tools, this program helps a lot.

Is it [MIT](https://en.wikipedia.org/wiki/MIT_License), some kind of [GPL](https://www.gnu.org/licenses/licenses.html) or else?

**Comment by dvingerh** [comment]
I've added a [GPL 3](https://github.com/dvingerh/transmission-renamer/blob/master/LICENSE) license.
